### ISSUE TITLE
Transmorgifying the Randomizer

### ISSUE THREAD

**Issue by LivingSynthesis** [StoneOrbits/VortexEngine#37]
The randomizer can be much more powerful and should be. Some cool new randomizer concepts:

-share your randomizer seed. automatically syncing randomization results so you don't need to share the results more than once.
    sending or receiving this could be triggered automatically when you enter the menu and the opposite by holding while in the menu.
-randomizer rules for custom single led pattern modes
-randomizer rules for parameters
-randomizer rules for patterns with color slots requiring colors

**Comment by Unreal-Dan** [comment]
We also talked about generating random LedMaps, or having a selection of pre-made LedMaps which could be used to apply different patterns to different leds in specific orientations.
